FORTUNE_BRAND := FortuneOS

FORTUNE_BUILD_DATE := $(shell date +%Y%m%d-%H%M)
FORTUNE_BUILD_DATE_UTC := $(shell date '+%Y-%m-%d %H:%M UTC %s')
FORTUNE_BUILD_VERSION := $(BUILD_ID)
FORTUNE_RELEASETYPE ?= release

FORTUNE_VERSION := $(FORTUNE_BRAND)_$(FORTUNE_BUILD)-$(BUILD_ID)-$(FORTUNE_BUILD_DATE)
